import type { iGalleryItem } from '@/types';

export const sampleItems: iGalleryItem[] = [
  // Jewelry Items
  {
    id: 'item1',
    categoryId: 'cat1',
    title: 'Sterling Silver North Star Ring',
    summary: 'Handcrafted sterling silver ring with intricate north star engraving.',
    description: 'This beautiful ring features a classic north star pattern meticulously engraved in sterling silver. The detailed design catches light beautifully and provides a timeless celestial look. Made using traditional silversmithing techniques with modern precision.',
    mainImageUrl: '/items/sterling_engraved_north_star_ring.jpeg',
    attributes: {
      'Material': 'Sterling Silver',
      'Size': '7-10 available',
      'Width': '6mm',
      'Weight': '4.2g',
      'Finish': 'Polished with Engraved Detail',
    },
    createdAt: '2024-01-20T14:30:00Z',
    updatedAt: '2024-01-20T14:30:00Z',
  },
  {
    id: 'item2',
    categoryId: 'cat1',
    title: 'Gold Signet Ring',
    summary: 'Classic gold signet ring with smooth polished finish.',
    description: 'A timeless gold signet ring crafted with traditional techniques. The smooth, polished surface provides the perfect canvas for personalization or can be worn as-is for a classic, understated look.',
    mainImageUrl: '/items/gold_signet_ring.jpeg',
    attributes: {
      'Material': '14k Gold',
      'Size': '6-12 available',
      'Width': '12mm',
      'Weight': '8.5g',
      'Finish': 'High Polish',
    },
    createdAt: '2024-01-18T09:15:00Z',
    updatedAt: '2024-01-18T09:15:00Z',
  },
  {
    id: 'item3',
    categoryId: 'cat1',
    title: 'Silver Ring with Onyx Stone',
    summary: 'Sterling silver ring featuring a deep black onyx centerpiece.',
    description: 'This striking ring combines the elegance of sterling silver with the dramatic beauty of natural onyx. The stone is securely set in a custom silver mounting that complements its deep black color.',
    mainImageUrl: '/items/silve_ring_with_onyx.jpeg',
    attributes: {
      'Material': 'Sterling Silver, Onyx',
      'Size': '7-11 available',
      'Stone Size': '8mm x 6mm',
      'Setting': 'Bezel Set',
      'Finish': 'Satin Silver',
    },
    createdAt: '2024-01-16T16:45:00Z',
    updatedAt: '2024-01-16T16:45:00Z',
  },
  {
    id: 'item4',
    categoryId: 'cat1',
    title: 'Gold Tiger Signet Ring',
    summary: 'Bold gold signet ring with detailed tiger engraving.',
    description: 'A powerful statement piece featuring an intricately engraved tiger design. This bold signet ring represents strength and courage, crafted with exceptional attention to detail in solid gold.',
    mainImageUrl: '/items/gold_tiger_signet_ring.jpeg',
    attributes: {
      'Material': '14k Gold',
      'Size': '7-13 available',
      'Width': '15mm',
      'Weight': '12.8g',
      'Design': 'Hand Engraved Tiger',
      'Finish': 'Textured with Polish Highlights',
    },
    createdAt: '2024-01-14T11:20:00Z',
    updatedAt: '2024-01-14T11:20:00Z',
  },
  {
    id: 'item5',
    categoryId: 'cat1',
    title: 'Silver Ring with Blue Stone',
    summary: 'Elegant silver ring featuring a brilliant blue gemstone.',
    description: 'This elegant ring showcases a beautiful blue stone set in sterling silver. The clean, modern design allows the stone to be the focal point while providing comfortable daily wear.',
    mainImageUrl: '/items/silver_blue_ring.jpeg',
    attributes: {
      'Material': 'Sterling Silver, Blue Topaz',
      'Size': '5-9 available',
      'Stone Size': '6mm round',
      'Setting': 'Prong Set',
      'Finish': 'Bright Polish',
    },
    createdAt: '2024-01-12T08:45:00Z',
    updatedAt: '2024-01-12T08:45:00Z',
  },

  // Leather Items
  {
    id: 'item6',
    categoryId: 'cat2',
    title: 'Hand-Stitched Brown Leather Belt',
    summary: 'Classic brown leather belt with traditional hand stitching.',
    description: 'This timeless brown leather belt is crafted from premium full-grain leather using traditional saddle stitching techniques. The rich brown color develops a beautiful patina with age and wear.',
    mainImageUrl: '/items/simple_leather_brown_belt.jpeg',
    attributes: {
      'Material': 'Full-Grain Leather',
      'Color': 'Rich Brown',
      'Width': '1.5"',
      'Thickness': '8-9 oz',
      'Stitching': 'Hand-Stitched',
      'Sizes Available': '30" - 44"',
    },
    createdAt: '2024-01-16T16:45:00Z',
    updatedAt: '2024-01-16T16:45:00Z',
  },
  {
    id: 'item7',
    categoryId: 'cat2',
    title: 'Brown Leather Belt with Gold Buckle',
    summary: 'Premium brown leather belt featuring an elegant gold-toned buckle.',
    description: 'A sophisticated leather belt that combines rich brown leather with a distinctive gold-toned buckle. Perfect for both casual and formal occasions, this belt adds a touch of elegance to any outfit.',
    mainImageUrl: '/items/brown_leather_belt_gold_buckle.jpeg',
    attributes: {
      'Material': 'Premium Leather',
      'Color': 'Cognac Brown',
      'Width': '1.25"',
      'Buckle': 'Gold-Toned Metal',
      'Edge': 'Hand-Finished',
      'Sizes Available': '32" - 42"',
    },
    createdAt: '2024-01-14T11:20:00Z',
    updatedAt: '2024-01-14T11:20:00Z',
  },
  {
    id: 'item8',
    categoryId: 'cat2',
    title: 'Black Leather Studded Belt',
    summary: 'Edgy black leather belt with metal stud detailing.',
    description: 'A bold statement piece featuring high-quality black leather adorned with metal studs. This belt combines traditional leatherwork with modern edge, perfect for those who want to make a statement.',
    mainImageUrl: '/items/bacl_leather_studded_belt.jpeg',
    attributes: {
      'Material': 'Black Leather',
      'Width': '1.5"',
      'Studs': 'Nickel-Plated Metal',
      'Pattern': 'Evenly Spaced Studs',
      'Edge': 'Burnished Black',
      'Sizes Available': '28" - 40"',
    },
    createdAt: '2024-01-12T08:45:00Z',
    updatedAt: '2024-01-12T08:45:00Z',
  },
  {
    id: 'item9',
    categoryId: 'cat2',
    title: 'Handcrafted Leather Hat',
    summary: 'Traditional leather hat with classic western styling.',
    description: 'This handcrafted leather hat showcases traditional western styling with modern comfort. Made from supple leather that shapes beautifully with wear, it provides both protection and timeless style.',
    mainImageUrl: '/items/leather_hat.jpeg',
    attributes: {
      'Material': 'Vegetable-Tanned Leather',
      'Style': 'Western/Cowboy',
      'Brim': '3.5" Wide',
      'Crown': 'Cattleman Crease',
      'Band': 'Leather with Conchos',
      'Sizes Available': 'S - XL',
    },
    createdAt: '2024-01-10T15:30:00Z',
    updatedAt: '2024-01-10T15:30:00Z',
  },
  {
    id: 'item10',
    categoryId: 'cat2',
    title: 'Brown Leather Work Glove',
    summary: 'Durable brown leather work glove with reinforced palms.',
    description: 'A heavy-duty work glove crafted from thick, durable leather. Features reinforced palms and fingertips for extended wear, while maintaining the flexibility needed for detailed work.',
    mainImageUrl: '/items/brown_leather_glove.jpeg',
    attributes: {
      'Material': 'Heavy-Duty Leather',
      'Color': 'Natural Brown',
      'Features': 'Reinforced Palm & Fingers',
      'Closure': 'Elastic Wrist',
      'Use': 'Work/Utility',
      'Sizes Available': 'S - XL',
    },
    createdAt: '2024-01-08T12:15:00Z',
    updatedAt: '2024-01-08T12:15:00Z',
  },
];
